version: '3.9'
services:
  cache:
    image: redis:latest
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $REDIS_LOCAL_PORT:$REDIS_DOCKER_PORT
    volumes: 
      - cache:/data
    networks:
      - dynamicconfiguration_default
  postgres:
    image: postgres:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - dynamicconfiguration_default
  app:
    depends_on:
      - postgres
      - cache
    build: .
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_URI=$POSTGRES_URI
    ports:
      - $PORT:$PORT
    volumes:
      - .:/usr/app
    networks:
      - dynamicconfiguration_default
networks:
  dynamicconfiguration_default:
    external: true

volumes: 
  postgres: {}
  cache: {}