version: '3.9'
services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE
    ports:
      - $MONGO_LOCAL_PORT:$MONGO_DOCKER_PORT
    volumes:
      - mongo:/data/db
  api:
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGODB_URI=$MONGO_URI
    ports:
      - $PORT:$PORT
    volumes:
      - .:/usr/app

volumes: 
  mongo: {}